name: Check Code Style

on:
  pull_request:
    branches:

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Шаг 3: Установка зависимостей и компиляция проекта
      - name: Install dependencies and compile
        run: |
          mvn clean compile

      # Шаг 4: Проверка стиля кода с помощью Checkstyle
      - name: Run Maven Checkstyle
        run: |
          mvn checkstyle:check
