name: Check Code Style

on:
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies and compile
        run: |
          mvn clean compile

      - name: Run Maven Checkstyle
        run: |
          mvn checkstyle:check